name: malison
version: 0.4.2
author: Bob Nystrom <robert@stuffwithstuff.com>
description: A little terminal UI package for the browser.
homepage: https://github.com/munificent/malison
dependencies:
  piecemeal: ">=0.2.0 <0.3.0"
dev_dependencies:
  browser: any
  unittest: any
